FROM orianna/tensorflow:latest
MAINTAINER Ziou Zheng <zhengziou@gmail.com>

# Install Pytorch
RUN pip --no-cache-dir install torch torchvision
RUN pip --no-cache-dir install tqdm


# Expose default port for tensorboard
EXPOSE 6006



